name: pdf-extractor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - notebook
  - pandas
  - numpy
  - pathlib
  - pip:
    - pymupdf4llm>=0.0.27
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
